# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('a_name', models.CharField(max_length=20)),
                ('a_code', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Desg',
            fields=[
                ('d_code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=20)),
                ('d_grade', models.CharField(max_length=10)),
                ('d_gdesig', models.CharField(max_length=20)),
                ('d_rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_eis', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('e_regsno', models.CharField(max_length=15)),
                ('e_name', models.CharField(max_length=40)),
                ('e_dob', models.DateField()),
                ('e_doj', models.DateField()),
                ('e_dot', models.DateField()),
                ('e_join', models.CharField(choices=[('Land_oustee', 'Land_oustee'), ('New_appointee', 'New_appointee'), ('Empty', 'Empty')], default='Empty', max_length=20)),
                ('e_termi', models.CharField(choices=[('Retirement', 'Retirement'), ('Death', 'Death'), ('VRS', 'VRS'), ('Empty', 'Empty')], default='Empty', max_length=20)),
                ('e_status', models.CharField(choices=[('In_Service', 'In_Service'), ('Not_in_service', 'Not_in_service')], default='In_service', max_length=20)),
                ('e_desg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpm_app.Desg')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('u_name', models.CharField(max_length=20)),
                ('u_type', models.CharField(max_length=2)),
                ('u_code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('u_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpm_app.Area')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='e_unit_roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onroll_unit', to='mpm_app.Unit'),
        ),
        migrations.AddField(
            model_name='employee',
            name='e_unit_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_unit', to='mpm_app.Unit'),
        ),
    ]
