# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='e_gender',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_join',
            field=models.CharField(choices=[('Land_oustee', 'Land_oustee'), ('New_appointee', 'New_appointee'), ('NA', 'NA')], default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_termi',
            field=models.CharField(choices=[('Retirement', 'Retirement'), ('Death', 'Death'), ('VRS', 'VRS'), ('NA', 'NA')], default='NA', max_length=20),
        ),
    ]
