# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpm_app', '0002_auto_20170911_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='desg',
            name='d_cadre',
            field=models.CharField(choices=[('CD', 'CD'), ('XCD', 'XCD')], default='CD', max_length=10),
        ),
        migrations.AddField(
            model_name='desg',
            name='d_discp',
            field=models.CharField(default='Empty', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desg',
            name='d_promo',
            field=models.CharField(default='Null', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desg',
            name='d_gdesig',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='desg',
            name='d_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
