# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpm_app', '0004_auto_20170911_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='u_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
