# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpm_app', '0005_unit_u_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_regsno',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
