# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpm_app', '0006_auto_20170911_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_doj',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_dot',
            field=models.DateField(null=True),
        ),
    ]
