# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-20 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpm_app', '0007_auto_20170911_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desg',
            name='d_code',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='DSCD'),
        ),
        migrations.AlterField(
            model_name='desg',
            name='d_discp',
            field=models.CharField(max_length=20, verbose_name='Discpline'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_desg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desg_code', to='mpm_app.Desg', verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_dob',
            field=models.DateField(blank=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_doj',
            field=models.DateField(blank=True, null=True, verbose_name='Service Join Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_dot',
            field=models.DateField(blank=True, null=True, verbose_name='Service Termination Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_eis',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='EIS No'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_join',
            field=models.CharField(choices=[('Land_oustee', 'Land_oustee'), ('New_appointee', 'New_appointee'), ('NA', 'NA')], default='NA', max_length=20, verbose_name='Service Join Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_name',
            field=models.CharField(max_length=40, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_regsno',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Unit Roll No'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_status',
            field=models.CharField(choices=[('In_service', 'In_service'), ('Not_in_service', 'Not_in_service')], default='In_service', max_length=20, verbose_name='Service Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_termi',
            field=models.CharField(choices=[('Retirement', 'Retirement'), ('Death', 'Death'), ('VRS', 'VRS'), ('NA', 'NA')], default='NA', max_length=20, verbose_name='Service Termination Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_unit_roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_unit_roll', to='mpm_app.Unit', verbose_name='On-Roll Unit'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_unit_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_unit_work', to='mpm_app.Unit', verbose_name='Working Unit'),
        ),
    ]
