# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-21 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpm_app', '0008_auto_20170920_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='a_abbr',
            field=models.CharField(default='', max_length=4, null=True),
        ),
    ]
