# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpm_app', '0009_area_a_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='e_dop',
            field=models.DateField(blank=True, null=True, verbose_name='Service Join Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_join',
            field=models.CharField(choices=[('NA', 'NA'), ('Land Losers', 'Land_Losers'), ('Fresh Recruitment', 'Fresh_Recruitment'), ('In lieu of Death', 'Death'), ('In lieu of perm Disability', 'Disability'), ('Female VRS', 'Female_VRS'), ('Reinstt_Rejoin', 'Reinstt_Rejoin'), ('Other reason(Inter Co transfer)', 'other_tranfer')], default='NA', max_length=20, verbose_name='Service Join Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_regsno',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Token No'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_termi',
            field=models.CharField(choices=[('NA', 'NA'), ('Retirement', 'Retirement'), ('Resignation', 'Resignation'), ('Medically Unfit', 'Unfit'), ('Death', 'Death'), ('Female VRS', 'Female_VRS'), ('VRS BPE', 'VRS'), ('Dismissal/Termination', 'Dismissal'), ('Other reason(Inter Co transfer)', 'other_tranfer')], default='NA', max_length=20, verbose_name='Service Termination Type'),
        ),
    ]
