# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-22 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpm_app', '0010_auto_20170922_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_dop',
            field=models.DateField(blank=True, null=True, verbose_name='Last promo. Date'),
        ),
    ]
