# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpm_app', '0011_auto_20170922_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='choices',
            fields=[
                ('c_value', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='value')),
                ('c_name', models.CharField(max_length=40, verbose_name='name')),
                ('c_category', models.CharField(max_length=40, verbose_name='category')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_join',
            field=models.CharField(choices=[('NA', 'NA'), ('Land_Losers', 'Appt of Land Losers'), ('Fresh_Recruitment', 'Fresh Recruitment'), ('Death', 'In lieu of Death'), ('Disability', 'In lieu of perm Disability'), ('Female_VRS', 'Female VRS'), ('Reinstt_Rejoin', 'Reinstt/Rejoin'), ('other_tranfer', 'Other reason(Inter Co transfer)')], default='NA', max_length=20, verbose_name='Service Join Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_termi',
            field=models.CharField(choices=[('NA', 'NA'), ('Retirement', 'Retirement'), ('Resignation', 'Resignation'), ('Unfit', 'Medically Unfit'), ('Death', 'Death'), ('Female VRS', 'Female_VRS'), ('VRS BPE', 'VRS'), ('Dismissal/Termination', 'Dismissal'), ('Other reason(Inter Co transfer)', 'other_tranfer')], default='NA', max_length=20, verbose_name='Service Termination Type'),
        ),
    ]
