# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-26 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpm_app', '0013_auto_20170926_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desg',
            name='d_gcode',
            field=models.CharField(max_length=5),
        ),
    ]
