# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-27 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mpm_app', '0014_auto_20170926_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateField(verbose_name='Addition Date')),
                ('a_edit_on', models.DateTimeField(verbose_name='Edit time')),
                ('a_edit_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Edited by')),
                ('a_eis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpm_app.Employee', verbose_name='Employee')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionCat',
            fields=[
                ('c_value', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='value')),
                ('c_name', models.CharField(max_length=40, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_date', models.DateField(verbose_name='Promote Date')),
                ('p_edit_on', models.DateTimeField(verbose_name='Edit time')),
                ('p_desg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpm_app.Desg', verbose_name='Designation')),
                ('p_edit_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Edited by')),
                ('p_eis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpm_app.Employee', verbose_name='Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_date', models.DateField(verbose_name='Termination Date')),
                ('t_edit_on', models.DateTimeField(verbose_name='Edit time')),
                ('t_edit_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Edited by')),
                ('t_eis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpm_app.Employee', verbose_name='Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TerminationCat',
            fields=[
                ('c_value', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='value')),
                ('c_name', models.CharField(max_length=40, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_category', models.CharField(choices=[('Transfer_In', 'Transfer In'), ('Transfer_Out', 'Transfer Out')], default='Transfer_In', max_length=20, verbose_name='Category')),
                ('th_date', models.DateField(verbose_name='Tranfer Date')),
                ('th_edit_on', models.DateTimeField(verbose_name='Edit time')),
                ('th_edit_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Edited by')),
                ('th_eis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpm_app.Employee', verbose_name='Employee')),
                ('th_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpm_app.Unit', verbose_name='On-Roll Unit')),
            ],
        ),
        migrations.AddField(
            model_name='termination',
            name='t_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpm_app.TerminationCat', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='addition',
            name='a_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpm_app.AdditionCat', verbose_name='Category'),
        ),
    ]
