# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-27 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpm_app', '0015_auto_20170927_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additioncat',
            old_name='c_name',
            new_name='ac_name',
        ),
        migrations.RenameField(
            model_name='additioncat',
            old_name='c_value',
            new_name='ac_value',
        ),
        migrations.RenameField(
            model_name='terminationcat',
            old_name='c_name',
            new_name='tc_name',
        ),
        migrations.RenameField(
            model_name='terminationcat',
            old_name='c_value',
            new_name='tc_value',
        ),
    ]
