# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-27 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpm_app', '0016_auto_20170927_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='a_eis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mpm_app.Employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='termination',
            name='t_eis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mpm_app.Employee', verbose_name='Employee'),
        ),
        migrations.AlterUniqueTogether(
            name='promotionhistory',
            unique_together=set([('p_eis', 'p_desg')]),
        ),
        migrations.AlterUniqueTogether(
            name='transferhistory',
            unique_together=set([('th_eis', 'th_unit', 'th_category', 'th_date')]),
        ),
    ]
