# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-27 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpm_app', '0017_auto_20170927_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_join',
            field=models.ForeignKey(default='A_NA', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='mpm_app.AdditionCat', verbose_name='Service Join Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_termi',
            field=models.ForeignKey(default='T_NA', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='mpm_app.TerminationCat', verbose_name='Service Termination Type'),
        ),
    ]
