# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-03 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpm_app', '0020_promotionhistory_p_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferhistory',
            name='th_prev_unit',
            field=models.ForeignKey(default='C09FLU', on_delete=django.db.models.deletion.CASCADE, related_name='th_prev_unit', to='mpm_app.Unit', verbose_name='On-Roll Unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='th_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='th_unit', to='mpm_app.Unit', verbose_name='On-Roll Unit'),
        ),
    ]
