# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-03 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpm_app', '0021_auto_20171003_1021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transferhistory',
            unique_together=set([('th_eis', 'th_unit', 'th_prev_unit', 'th_date')]),
        ),
        migrations.RemoveField(
            model_name='transferhistory',
            name='th_category',
        ),
    ]
